#%RAML 0.8
title: YaaS-Platform-Info-Service
baseUri: http://localhost/
version: v1
mediaType:  application/json

schemas:
  - regions: !include ./schemata/regions_collection.json
  - region: !include schemata/region_entity.json
  - markets: !include schemata/markets_collection.json
  - market: !include schemata/market_entity.json
  - error: !include https://api.yaas.io/patterns/v1/schema-error-message.json

traits:
  - !include https://api.yaas.io/patterns/v2/trait-yaas-aware.yaml

resourceTypes:
  - !include https://api.yaas.io/patterns/v2/resource-type-element.yaml
  - !include https://api.yaas.io/patterns/v1/resource-type-collection.yaml

/regions:
  type: collection
  get:
    description: Gets all YaaS regions
    responses:
      200:
        body:
          application/json:
            example: !include examples/regions.json

  /{regiontId}:
    type: element
    uriParameters:
      regiontId:
        description: the id of the wishlist to work on
        example: EU
        type: string
        minLength: 2
        enum:
          - US
          - EU
          - _beta_
    get:
      description: Gets a wishlist
      responses:
        200:
          body:
            application/json:
              example: !include examples/region.json

/markets:
  get:
    description: Gets all YaaS markets
    responses:
      200:
        body:
          application/json:
            example: !include examples/markets.json

  /{marketId}:
    uriParameters:
      marketId:
        displayName: Market Identifier
        description: id of the market to retrieve information for
        example: US
        type: string
        minLength: 2
        enum:
          - US
          - DE
          - _beta_
    get:
      description: Gets a market information
      responses:
        200:
          body:
            application/json:
              example: !include examples/market.json

/info:
  get:
    queryParameters:
      ip:
        type: string
    responses:
      200:

  /{ip}:
    uriParameters:
      ip:
        displayName: IP address
    get:
      responses:
        200:

/email:
  displayName: Email check
  get:
    queryParameters:
      address:
        type: string
        displayName: Email address
    responses:
      200:
        body:
          application/json:

  /{address}:
    uriParameters:
      address:
        example: john_smith@abc.com
        minLength: 3
        maxLength: 254
        pattern: ^[^@]+@[^@]+.[a-z]$
        displayName: Email adress
    get:
      responses:
        200:

/vatin/{country}/{vatin}:
  displayName: Vatin check
  get:
  uriParameters:
   country:
     displayName: Country
     enum:
       - DE
     maxLength: 2
     minLength: 2
   vatin:
     displayName: VAT Identification Number
     minLength: 2
