#!/usr/bin/env sh
# shellcheck disable=SC2039

readonly VERSION='1.0.1'
readonly AUTHOR='Ralf Hofmann'
readonly CONTACT='<r.hofmann@sap.com>'

# Disposable Email Address (DEA) - data source
# https://github.com/ivolo/disposable-email-domains
# https://github.com/martenson/disposable-email-domains
# https://github.com/lodow/disposable-email-domains-1
# https://github.com/MattKetmo/EmailChecker
readonly EMAIL_DISPOSAL_URL=https://github.com/ivolo/disposable-email-domains/raw/master/index.json
readonly EMAIL_WILDCARD_URL=https://github.com/ivolo/disposable-email-domains/raw/master/wildcard.json
readonly EMAIL_WHITELIST_URL=https://github.com/lodow/disposable-email-domains-1/raw/master/whitelist.conf

readonly EMAIL_DOMAINS_FILE='Email-Domains.db'
readonly EMAIL_DOMAINS_FOLDER="${DATA_FOLDER}/email"

###########################################################################
# main functionality of the script
###########################################################################
main()
{
  # initialize all global variables
  _initialize

  # Process command line arguments
  # Options followed by one colon indicate having required argument
  OPTSTR=$(getopt -o Fhv --long force,help,version -n "${SCRIPT_NAME}" -- "$@") || _usage
  eval set -- "$OPTSTR"
  while true ; do
    case "$1" in
      '-F'|'--force')   FORCE=1  ; shift ;;
      '-h'|'--help')    _help    ; exit  ;;
      '-v'|'--version') _version ; exit  ;;
      '--')             shift    ; break ;;
      *)                _usage           ;;
    esac
  done

  if [ $# -gt 1 ]; then
    _usage; _error_exit "too many command line parameter"
  fi

  local EMAIL_DOMAINS_PATH="${EMAIL_DOMAINS_FOLDER}/${EMAIL_DOMAINS_FILE}"
  if [ $# -eq 1 ]; then
    EMAIL_DOMAINS_PATH="$1"
    shift
  fi

  [ -d "$(dirname -- "${EMAIL_DOMAINS_PATH}")" ] || \
    (EMAIL_FOLDER="$(dirname -- "${EMAIL_DOMAINS_PATH}")" ; \
     mkdir -p "${EMAIL_FOLDER}" ; \
     EMAIL_PARENT="$(dirname -- "${EMAIL_FOLDER}")" ; \
     chown "$(stat -c %u "${EMAIL_PARENT}")":"$(stat -c %g "${EMAIL_PARENT}")" "${EMAIL_FOLDER}")

  provide_domains_database "${EMAIL_DOMAINS_PATH}" "${FORCE:-0}"
}


provide_domains_database()
{
  command -v curl >/dev/null 2>&1 || _error_exit "curl needs to be installed for downloading email data"

  local DB_FILE DB_FORCE DB_META DB_UID DB_GID DB_DATA
  local EMAIL_DATA_DISPOSAL EMAIL_DATA_WILDCARD EMAIL_DATA_WILDCARD

  DB_FILE="$1"        # db file path
  DB_FORCE="${2:-0}"  # flag to force db update

  DB_META="${DB_FILE}"

  [ -f "${DB_META}" ] || DB_META="$(dirname -- "${DB_META}")"

  DB_UID="$(stat -c %u "${DB_META}")"
  DB_GID="$(stat -c %g "${DB_META}")"

  if [ "${DB_FORCE}" -eq 0 ] && [ -f "${DB_FILE}" ] && \
     [ "$(curl -kSLIs -z"${DB_FILE}" -w "%{http_code}" "${EMAIL_DISPOSAL_URL}" | tail -1)" = "304" ] && \
     [ "$(curl -kSLIs -z"${DB_FILE}" -w "%{http_code}" "${EMAIL_WILDCARD_URL}" | tail -1)" = "304" ] && \
     [ "$(curl -kSLIs -z"${DB_FILE}" -w "%{http_code}" "${EMAIL_WHITELIST_URL}" | tail -1)" = "304" ]; then
    _message -s -i "Email domain database '${DB_FILE}' is already up-to-date..."
    return
  fi

  # shellcheck disable=SC2119
  EMAIL_DATA_DISPOSAL="$(_make_temp)".'csv'
  # shellcheck disable=SC2119
  EMAIL_DATA_WILDCARD="$(_make_temp)".'csv'
  # shellcheck disable=SC2119
  EMAIL_DATA_WHITELIST="$(_make_temp)".'csv'

  command -v jq >/dev/null 2>&1 || _error_exit "jq needs to be installed for process email data"
  _message -s -i "downloading disposal email domain data file from url: '${EMAIL_DISPOSAL_URL}'..."
  curl -jkSLR -'#' "${EMAIL_DISPOSAL_URL}" | jq -r '.|@csv' | tr , '\n' >"${EMAIL_DATA_DISPOSAL}" || _error_exit "failed to download data from url: '${EMAIL_DISPOSAL_URL}'"
  _message -s -i "downloading wildcard email domain data file from url: '${EMAIL_WILDCARD_URL}'..."
  curl -jkSLR -'#' "${EMAIL_WILDCARD_URL}" | jq -r '.|@csv' | tr , '\n' >"${EMAIL_DATA_WILDCARD}" || _error_exit "failed to download data from url: '${EMAIL_WILDCARD_URL}'"
  _message -s -i "downloading whitelist email domain data file from url: '${EMAIL_WHITELIST_URL}'..."
  curl -jkSLR -'#' "${EMAIL_WHITELIST_URL}" >"${EMAIL_DATA_WHITELIST}" || _error_exit "failed to download data from url: '${EMAIL_WHITELIST_URL}'"

  # shellcheck disable=SC2119
  DB_DATA="$(_make_temp)"

  if import_domain_data_files "${DB_DATA}" "${EMAIL_DATA_DISPOSAL}" "${EMAIL_DATA_WILDCARD}" "${EMAIL_DATA_WHITELIST}"; then
    mv -f "${DB_DATA}" "${DB_FILE}"
    chown "${DB_UID}":"${DB_GID}" "${DB_FILE}"
    chmod a+r "${DB_FILE}"
    _message -s -i "updated email domain database '${DB_FILE}'"
  else
    _error_exit "failed to import email domain data"
  fi

  # remove data files
  [ "${_VERBOSE_:-0}" -lt 4 ] && \
    (rm -f "${EMAIL_DATA_DISPOSAL}"  \
           "${EMAIL_DATA_WILDCARD}"  \
           "${EMAIL_DATA_WHITELIST}" \
           "${DB_DATA}"              \
    >/dev/null 2>&1 || :)
}

import_domain_data_files()
{
  command -v sqlite3 >/dev/null 2>&1 || _error_exit "sqlite3 needs to be installed for creating GeoIP network database"

  local DB_FILE DISPOSAL_DATA WILDCARD_DATA WHITELIST_DATA ECHO_DIRECTIVE

  DB_FILE="$1"

  DISPOSAL_DATA="$2"
  WILDCARD_DATA="$3"
  WHITELIST_DATA="$4"

  [ -f "${DISPOSAL_DATA}" ]  || ( _message -s -e "disposal email domains data file '${DISPOSAL _DATA}' is not accessible" ; return 1 )
  [ -f "${WILDCARD_DATA}" ]  || ( _message -s -e "wildcard email domains data file '${WILDCARD_DATA}' is not accessible"  ; return 1 )
  [ -f "${WHITELIST_DATA}" ] || ( _message -s -e "whitelist email domains data file '${WHITELIST_DATA}' i t accessible"   ; return 1 )

  ECHO_DIRECTIVE='.echo'

  if [ "${_VERBOSE_:-0}" -gt 4 ]; then
    ECHO_DIRECTIVE="${ECHO_DIRECTIVE} on"
  else
    ECHO_DIRECTIVE="${ECHO_DIRECTIVE} off"
  fi

  # shellcheck disable=SC2119
  _trim << -SQL- | sqlite3 "${DB_FILE}"

    -- SQL commands begin ------------------------------------------------------

    ${ECHO_DIRECTIVE}

    -- create domains if not existing

    DROP TABLE IF EXISTS domains;

    CREATE TABLE domains(domain TEXT NOT NULL CHECK(length(domain) > 3),
                         is_wildcard INTEGER NOT NULL DEFAULT 0 CHECK(is_wildcard = 0 OR is_wildcard = 1)
                        );

    CREATE TEMPORARY VIEW IF NOT EXISTS domains_import(domain
                                                      ) AS SELECT domain
                                                        FROM Domains;

    CREATE TRIGGER IF NOT EXISTS insert_domains INSTEAD OF
      INSERT ON domains_import
      BEGIN
        INSERT INTO domains(domain, is_wildcard)
          VALUES(NEW.domain, 0);
      END;

    .mode csv
    .separator ','
    .import "${DISPOSAL_DATA}" domains_import

    DROP TRIGGER IF EXISTS insert_domains;

    CREATE TRIGGER IF NOT EXISTS insert_domains INSTEAD OF
      INSERT ON domains_import
      BEGIN
        INSERT INTO domains(domain, is_wildcard)
          VALUES(NEW.domain, 1);
      END;

    .mode csv
    .separator ','
    .import "${WILDCARD_DATA}" domains_import

    DROP TRIGGER IF EXISTS insert_domains;

    DROP VIEW IF EXISTS domains_import;

    -- SQL commands end --------------------------------------------------------

-SQL-

  # shellcheck disable=SC2119
  _trim << -SQL- | sqlite3 "${DB_FILE}"

    -- SQL commands begin ------------------------------------------------------

    ${ECHO_DIRECTIVE}

    -- create whitelist if not existing

    DROP TABLE IF EXISTS whitelist;

    CREATE TABLE whitelist(domain TEXT NOT NULL CHECK(length(domain) > 3));

    .mode csv
    .separator ','
    .import "${WHITELIST_DATA}" whitelist

    -- SQL commands end --------------------------------------------------------

-SQL-
}


###########################################################################
# customized functions
###########################################################################
_usage() {
	printf >&2 'usage: %s [-h|--help] [-v|--version] [-F|--force] [<db file>]\n' "${SCRIPT_NAME}" && exit 1
}

_help() {
cat <<- -EOF-

  ${SCRIPT_NAME} Version ${VERSION}
  by ${AUTHOR} ${CONTACT}

  Simple script to provide email domain database file

  ${SCRIPT_NAME} [-h|--help] [-v|--version] [-f|--force] [<db file>]

    <db file>  email domain database as full path [${EMAIL_DOMAINS_FOLDER}/${EMAIL_DOMAINS_FILE}]

  Options:

    -h, --help      Display this help message and exit.
    -v, --version   Display version and exit.
    -F, --force     Force update of the database.

-EOF-
}

### begin -- ormos/utility : 1.1.0 / 27-FEB-2017
###########################################################################
# utility functions
###########################################################################

#
# Output version information
#
# shellcheck disable=SC2120
_version() {
  _message -s -f 'Version %s by %s %s\n' "${VERSION}" "${AUTHOR}" "${CONTACT}"
}

#
# Intialize global settings
#
# shellcheck disable=SC2120
_initialize()
{
  set -o nounset -o errexit ; [ -n "${BASH:-}" ] && set -eo pipefail ; [ -n "${_TRACE_:-}" ] && set -x

  # Set file creation mask so that all files are created with 600 permissions.
  # This will help protect temp files.
  umask 066

  # the full qualified path of the script
  # shellcheck disable=SC2034
  SCRIPT_PATH=$(dirname -- "$(_real_path "$0")")
  SCRIPT_NAME=$(basename -- "$0")
  TMP_FOLDER="${TMPDIR:-/tmp/$(id -u)}/${SCRIPT_NAME}-$$"

  # make sure temp folder exists
  [ -d "${TMP_FOLDER}" ] || mkdir -p "${TMP_FOLDER}"

  # verbose level
  _VERBOSE_=${_VERBOSE_:-0}

  # Trap TERM, HUP, and INT signals and properly exit
  trap -- '__exit_handler' EXIT
  trap -- '__terminate_handler' TERM HUP
  trap -- '__abort_handler' INT
}

#
# Output formatted error or text messages
#
# Options:
#   -s Script name used prefix.
#   -e Output error message
#   -w Output warning message
#   -i Output information message
#   -f Printf like format string
#
# Arguments:
#   '-' read message from stdin
#   <*> string holding text message as parameter
#
# shellcheck disable=SC2120
_message()
{
  local IDNX CATG LEN FMT TXT_IDNX TXT_CATG TXT_PRFX TXT_MSG LEN_PRFX=0

  while [ $# -gt 0 ]; do
    case $1 in
      -s ) IDNX="${SCRIPT_NAME}"; shift ;;
      -e ) CATG='ERROR'         ; shift ;;
      -w ) CATG='WARNING'       ; shift ;;
      -i ) CATG='INFO'          ; shift ;;
      -f ) FMT=$2 ; shift       ; shift ;;
      -- ) break                ; shift ;;
      * )  break                          ;;
    esac
  done

  if [ -n "${IDNX:-}" ]; then
    TXT_IDNX="$(printf '%s - ' "$IDNX")"
    LEN_PRFX=$((${#IDNX} + 3))
    TXT_PRFX="$TXT_IDNX"
  fi
  if [ -n "${CATG:-}" ]; then
    TXT_CATG="$(printf '%s: ' "$CATG")"
    LEN_PRFX=$((${#CATG} + 2))
    TXT_PRFX="${TXT_PRFX:-}$TXT_CATG"
  fi

  # check if we should indent
  [ "${LEN:-0}" -lt $LEN_PRFX ] || LEN_PRFX=${LEN:-0}

  # format the output using the format string or default
  # shellcheck disable=SC2059
  if [ -n "${FMT:-}" ]; then
    if [ $# -eq 0 ] || ([ $# -eq 1 ] && [ "$1" = '-' ]); then
      TXT_MSG="$(printf "${FMT}" "$(cat -)")"
    else
      TXT_MSG="$(printf "${FMT}" "$@")"
    fi
  else
    if [ $# -eq 0 ] || ([ $# -eq 1 ] && [ "$1" = '-' ]); then
      TXT_MSG="$(cat -)"
    else
      TXT_MSG="$(printf "$@")"
    fi
  fi

  printf '%*s%s\n' "$LEN_PRFX" "${TXT_PRFX:-}" "$TXT_MSG"
}

#
# Returns string indented by 4 spaces
#
# Arguments:
#   '-' read string from stdin
#   <*> string as parameter
#
# shellcheck disable=SC2120
_indent()
{
  local INDENT='    '

  if [ $# -eq 0 ] || ([ $# -eq 1 ] && [ "$1" = '-' ]); then
    sed -e "s/^/${INDENT}/g"
  else
    # shellcheck disable=SC2001
    echo "$@" | sed -e "s/^/${INDENT}/g"
  fi
}

#
# Returns lowercase string
#
# Arguments:
#   '-' read string from stdin
#   <*> string as parameter
#
# shellcheck disable=SC2120
_tolower()
{
  if [ $# -eq 0 ] || ([ $# -eq 1 ] && [ "$1" = '-' ]); then
    tr '[:upper:]' '[:lower:]'
  else
    echo "$@" | tr '[:upper:]' '[:lower:]'
  fi
}

#
# Returns uppercase string
#
# Arguments:
#   '-' read string from stdin
#   <*> string as parameter
#
# shellcheck disable=SC2120
_toupper()
{
  if [ $# -eq 0 ] || ([ $# -eq 1 ] && [ "$1" = '-' ]); then
    tr '[:lower:]' '[:upper:]'
  else
    echo "$@" | tr '[:lower:]' '[:upper:]'
  fi
}

#
# Trims any leading and trailing tabs or spaces
#
# Arguments:
#   '-' read string from stdin
#   <*> string as parameter
#
# shellcheck disable=SC2120
_trim()
{
  # local VAR="$@"
  # VAR="${VAR#"${VAR%%[![:space:]]*}"}" # remove leading whitespace characters
  # VAR="${VAR%"${VAR##*[![:space:]]}"}" # remove trailing whitespace characters
  # echo "${VAR}"

  if [ $# -eq 0 ] || ([ $# -eq 1 ] && [ "$1" = '-' ]); then
    sed -e 's/^[[:space:]]*//;s/[[:space:]]*$//'
  else
    echo "$@" | sed -e 's/^[[:space:]]*//;s/[[:space:]]*$//'
  fi
}

#
# Function for outputting a time stamp
#
# shellcheck disable=SC2120
_time_stamp()
{
  date -u +%Y-%m-%dT%H:%M:%S%z
}

#
# Function for exit due to fatal program error
#
# Arguments:
#   '-' read message from stdin
#   <1> string holding text message as parameter
#   <2> exit code
#
# shellcheck disable=SC2120
_error_exit()
{
  local MESSAGE

  if [ "${1:-}" = '-' ]; then
    MESSAGE="$(cat -)"
  else
    MESSAGE="${1:-}"
  fi

  _message -s -e "${MESSAGE:-Unknown Error}"  >&2

  exit "${2:-1}"
}

#
# Function to perform action on script exit
#
__exit_handler()
{
  __do_cleanup
}

#
# Function to perform exit if termination signal is trapped
#
__terminate_handler()
{
  _message -s -w "Terminated" >&2

  exit
}

#
# Function to perform exit if interrupt signal is trapped
#
 __abort_handler()
{
  _message -s -w "Aborted by user" >&2

  exit
}

#
# Function to remove temporary files and other housekeeping
#
__do_cleanup()
{
  # remove the temp folder
  [ "${_VERBOSE_:-0}" -lt 3 ] && [ -d "${TMP_FOLDER}" ] && \
    (rm -rf "${TMP_FOLDER}" >/dev/null 2>&1 || :)

  return 0
}

# Function to create a temporary files or folder
#
# Options:
#   -d Create directory instead of file
#
# Arguments:
#   <1> Name mask pattern to use
#
# shellcheck disable=SC2120
_make_temp()
{
  local TMPOPTS='-p'

  if [ "${1:-}" = '-d' ]; then
    TMPOPTS="-d ${TMPOPTS}" ; shift;
  fi
  local TMPMASK="${1:-${SCRIPT_NAME}-XXXXXX}"

  # shellcheck disable=SC2086
  mktemp ${TMPOPTS} "${TMP_FOLDER}" "${TMPMASK}"
}

# Function to retrieve a full filesystem path
#
# Arguments:
#   <1> Absolute or relative filesystem path
#
# shellcheck disable=SC2120
_real_path()
{
  local PTH="${1:-.}"

  if [ -d "$(dirname -- "${PTH}")" ]; then
    # shellcheck disable=SC2155
    local _readlink="$(command -v greadlink || command -v readlink || :)"
    ([ "${_readlink}" ] && "${_readlink}" -f "${PTH}") || \
    ([ -d "${PTH}" ] && (cd "${PTH}"; pwd)) || \
    (cd "$(dirname -- "${PTH}")"; case "${PWD}" in */) echo "${PWD}$(basename -- "${PTH}")"  ;;
                                                    *) echo "${PWD}/$(basename -- "${PTH}")" ;;
                              esac )
  else
    case "${PTH}" in /*) echo "${PTH}" ;; *) echo "${PWD}/${PTH}" ;; esac | \
      (
        local PTS ; IFS=/
        # shellcheck disable=SC2013
        for P in $(cat); do
          case "${P}" in
            ''|'.') ;;
              '..') PTS="$(dirname -- "${PTS}")" ;;
                 *) case "${PTS}" in */) PTS="${PTS}${P}"  ;;
                                      *) PTS="${PTS}/${P}" ;;
                    esac ;;
          esac
        done
        echo "${PTS:-}"
      )
  fi
}

###########################################################################
# Execution starts here
###########################################################################
main "$@"

### end -- ormos/utility : 1.1.0 / 27-FEB-2017